# -*- coding: utf-8 -*-
"""delhi_metro_trips.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s6TKW9Bo4P_H8ZcN0I4zYUpZQhAXYXko
"""

#load json data from git

import pandas as pd

url = "https://raw.githubusercontent.com/madhavipathipaka17/metro-pulse-delhi-analytics-/main/source_data/delhi_metro_trips.json"

data = pd.read_json(url)
data

data

data.info()

data.columns=data.columns.str.strip().str.lower()

data.columns

data['from_station']=data['from_station'].str.strip()
data['to_station']=data['to_station'].str.strip()
data['from_station']=data['from_station'].str.lower().str.title()
data['to_station']=data['to_station'].str.lower().str.title()

data.to_csv("delhi_metro_trips.csv", index=False)

data['ticket_type']=data['ticket_type'].replace('None', pd.NA)
data['ticket_type']=data['ticket_type'].fillna('Unknown')
data['remarks']=data['remarks'].replace('', pd.NA)
data['remarks']=data['remarks'].fillna('Others')
data.to_csv("delhi_metro_trips.csv", index=False)

data[['distance_km','fare','cost_per_passenger','passengers']]=data[['distance_km','fare','cost_per_passenger','passengers']].round(2)
data.to_csv("delhi_metro_trips.csv", index=False)
data

count = (data['from_station'] == data['to_station']).sum()
print(count)

data = data[data['from_station'] != data['to_station']]
data.to_csv("delhi_metro_trips.csv", index=False)

count = (data['from_station'] == data['to_station']).sum()
print(count)

data = data.copy()
data['date']=pd.to_datetime(data['date'],errors='coerce')
data.to_csv("delhi_metro_trips.csv", index=False)

data["date"].isna().sum()

numeric_cols = ['distance_km', 'fare', 'cost_per_passenger', 'passengers']

for col in numeric_cols:
    data[col] = pd.to_numeric(data[col], errors='coerce')
data.to_csv("delhi_metro_trips.csv", index=False)

data = data.drop_duplicates()

print(data.isnull().sum())

print(data.info())
print(data.head())

print(data[['from_station','to_station']].head(10))

data.info()

# Save as CSV
data.to_csv("delhi_metro_trips.csv", index=False)

print("File converted to CSV successfully!")

"""# New section"""